### ISSUE TITLE
Add IDs for inputs and HTMLFor for labels

### ISSUE THREAD

**Issue by riungemaina** [castynet-studios/pms-fe#40]
in the file 
[src/pages/addPig/addPig.tsx](https://github.com/castynet-studios/pms-fe/blob/main/src/pages/addPig/addPig.tsx)

**Comment by Omafovbe** [comment]
hello @riungemaina would love to take on this issue.  Do you mind?

**Comment by riungemaina** [comment]
Hello 👋
Yes, you can pick it up..
If you need any details please let me know.
PS: The convention is to use camelCase even for IDs.

**Comment by Omafovbe** [comment]
Thanks for the opportunity. In as much we wish to use a naming convention
of camelCase for some of the IDs do you mind i include *pig *eg *pigAge or
pigBreed*
